version: '3.9'

services:
  fastapi:
    build: .
    container_name: fastapi_app
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - redis
    command: >
      sh -c "
        /wait-for-it.sh elasticsearch:9200 --timeout=30 --strict -- 
        /wait-for-it.sh redis:6379 --timeout=30 --strict -- 
        uvicorn main:app --host 0.0.0.0 --port 8000
      "

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  esdata:
